var React = require('react');

var rawCodes = [
  { code: "AF", verbose: "Afganistán (Emirato Islámico de)" },
  { code: "AL", verbose: "Albania (República de)" },
  { code: "DE", verbose: "Alemania (República Federal de)" },
  { code: "AD", verbose: "Andorra (Principado de)" },
  { code: "AO", verbose: "Angola (República de)" },
  { code: "AI", verbose: "Anguila" },
  { code: "AQ", verbose: "Antártida" },
  { code: "AG", verbose: "Antigua y Barbuda (Comunidad Británica de Naciones)" },
  { code: "SA", verbose: "Arabia Saudita (Reino de)" },
  { code: "DZ", verbose: "Argelia (República Democrática y Popular de)" },
  { code: "AR", verbose: "Argentina (República)" },
  { code: "AM", verbose: "Armenia (República de)" },
  { code: "AW", verbose: "Aruba (Territorio Holandés de Ultramar)" },
  { code: "AU", verbose: "Australia (Comunidad de)" },
  { code: "AT", verbose: "Austria (República de)" },
  { code: "AZ", verbose: "Azerbaijan (República Azerbaijani)" },
  { code: "BS", verbose: "Bahamas (Comunidad de las)" },
  { code: "BH", verbose: "Bahréin (Estado de)" },
  { code: "BD", verbose: "Bangladesh (República Popular de)" },
  { code: "BB", verbose: "Barbados (Comunidad Británica de Naciones)" },
  { code: "BY", verbose: "Belarus" },
  { code: "BE", verbose: "Bélgica (Reino de)" },
  { code: "BZ", verbose: "Belice " },
  { code: "BJ", verbose: "Benín (República de)" },
  { code: "BM", verbose: "Bermudas" },
  { code: "BO", verbose: "Bolivia (República de)" },
  { code: "BQ", verbose: "Bonaire, San Eustaquio y Saba" },
  { code: "BA", verbose: "Bosnia y Herzegovina" },
  { code: "BW", verbose: "Botswana (República de)" },
  { code: "BR", verbose: "Brasil (República Federativa de)" },
  { code: "BN", verbose: "Brunei (Estado de) (Residencia de Paz)" },
  { code: "BG", verbose: "Bulgaria (República de)" },
  { code: "BF", verbose: "Burkina Faso" },
  { code: "BI", verbose: "Burundi (República de)" },
  { code: "BT", verbose: "Bután (Reino de)" },
  { code: "CV", verbose: "Cabo Verde (República de)" },
  { code: "KH", verbose: "Camboya (Reino de)" },
  { code: "CM", verbose: "Camerún (República del)" },
  { code: "CA", verbose: "Canadá" },
  { code: "TD", verbose: "Chad (República del)" },
  { code: "CL", verbose: "Chile (República de)" },
  { code: "CN", verbose: "China (República Popular)" },
  { code: "CY", verbose: "Chipre (República de)" },
  { code: "VA", verbose: "Ciudad del Vaticano (Estado de la)" },
  { code: "CO", verbose: "Colombia (República de)" },
  { code: "CG", verbose: "Congo (Brazzaville)" },
  { code: "CD", verbose: "Congo (la República Democrática del)" },
  { code: "KR", verbose: "Corea (República de) (Corea del Sur)" },
  { code: "KP", verbose: "Corea (República Popular Democrática de) (Corea del Norte)" },
  { code: "CI", verbose: "Costa de Marfil (República de la)" },
  { code: "CR", verbose: "Costa Rica (República de)" },
  { code: "HR", verbose: "Croacia (República de)" },
  { code: "CU", verbose: "Cuba (República de)" },
  { code: "CW", verbose: "Curaçao" },
  { code: "DK", verbose: "Dinamarca (Reino de)" },
  { code: "DM", verbose: "Dominica (Comunidad de)" },
  { code: "EC", verbose: "Ecuador (República del)" },
  { code: "EG", verbose: "Egipto (República Árabe de)" },
  { code: "SV", verbose: "El Salvador (República de)" },
  { code: "AE", verbose: "Emiratos Árabes Unidos" },
  { code: "ER", verbose: "Eritrea (Estado de)" },
  { code: "SK", verbose: "Eslovaquia" },
  { code: "SI", verbose: "Eslovenia (República de)" },
  { code: "ES", verbose: "España (Reino de)" },
  { code: "UM", verbose: "Estados Unidos (Islas Menores Alejadas)" },
  { code: "US", verbose: "Estados Unidos de America" },
  { code: "EE", verbose: "Estonia (República de)" },
  { code: "ET", verbose: "Etiopia (República Democrática Federal)" },
  { code: "PH", verbose: "Filipinas (República de las)" },
  { code: "FI", verbose: "Finlandia (República de)" },
  { code: "FJ", verbose: "Fiyi" },
  { code: "FR", verbose: "Francia (República Francesa)" },
  { code: "GA", verbose: "Gabonesa (República)" },
  { code: "GM", verbose: "Gambia (República de la)" },
  { code: "GE", verbose: "Georgia (República de)" },
  { code: "GS", verbose: "Georgia del Sur e Islas Sándwich" },
  { code: "GH", verbose: "Ghana (República de)" },
  { code: "GI", verbose: "Gibraltar (R.U.)" },
  { code: "GD", verbose: "Granada" },
  { code: "GR", verbose: "Grecia (República Helénica)" },
  { code: "GL", verbose: "Groenlandia (Dinamarca)" },
  { code: "GP", verbose: "Guadalupe (Departamento de)" },
  { code: "GU", verbose: "Guam (E.U.A.)" },
  { code: "GT", verbose: "Guatemala (República de)" },
  { code: "GY", verbose: "Guayana" },
  { code: "GF", verbose: "Guayana Francesa" },
  { code: "GG", verbose: "Guernesey" },
  { code: "GN", verbose: "Guinea (República de)" },
  { code: "GQ", verbose: "Guinea Ecuatorial (República de)" },
  { code: "GW", verbose: "Guinea-Bissau (República de)" },
  { code: "HT", verbose: "Haití (República de)" },
  { code: "HN", verbose: "Honduras (República de)" },
  { code: "HK", verbose: "Hong Kong (Región Administrativa Especial de la República)" },
  { code: "HU", verbose: "Hungría (República de)" },
  { code: "IN", verbose: "India (República de)" },
  { code: "ID", verbose: "Indonesia (República de)" },
  { code: "IQ", verbose: "Irak (República de)" },
  { code: "IR", verbose: "Irán (República Islámica del)" },
  { code: "IE", verbose: "Irlanda (República de)" },
  { code: "BV", verbose: "Isla Bouvet" },
  { code: "IM", verbose: "Isla de Man" },
  { code: "CX", verbose: "Isla de Navidad" },
  { code: "NF", verbose: "Isla Norfolk" },
  { code: "IS", verbose: "Islandia (República de)" },
  { code: "KY", verbose: "Islas Caimán" },
  { code: "CC", verbose: "Islas Cocos (Keeling)" },
  { code: "KM", verbose: "Islas Comoros" },
  { code: "CK", verbose: "Islas Cook" },
  { code: "FO", verbose: "Islas Feroe" },
  { code: "HM", verbose: "Islas Heard y McDonald" },
  { code: "FK", verbose: "Islas Malvinas (Falkland)" },
  { code: "MP", verbose: "Islas Marianas del Norte" },
  { code: "MH", verbose: "Islas Marshall" },
  { code: "PN", verbose: "Islas Pitcairn" },
  { code: "SB", verbose: "Islas Salomón (Comunidad Británica de Naciones)" },
  { code: "TC", verbose: "Islas Turcas y Caicos" },
  { code: "VG", verbose: "Islas Vírgenes Británicas" },
  { code: "VI", verbose: "Islas Vírgenes de EE. UU." },
  { code: "AX", verbose: "Islas Åland" },
  { code: "IL", verbose: "Israel (Estado de)" },
  { code: "IT", verbose: "Italia (República Italiana)" },
  { code: "JM", verbose: "Jamaica" },
  { code: "JP", verbose: "Japón" },
  { code: "JE", verbose: "Jersey" },
  { code: "JO", verbose: "Jordania (Reino Hachemita de)" },
  { code: "KZ", verbose: "Kazakhstan (República de)" },
  { code: "KE", verbose: "Kenya (República de)" },
  { code: "KG", verbose: "Kirguistán" },
  { code: "KI", verbose: "Kiribati (República de)" },
  { code: "KW", verbose: "Kuwait (Estado de)" },
  { code: "LA", verbose: "Laos" },
  { code: "LS", verbose: "Lesotho (Reino de)" },
  { code: "LV", verbose: "Letonia (República de)" },
  { code: "LB", verbose: "Líbano (República de)" },
  { code: "LR", verbose: "Liberia (República de)" },
  { code: "LY", verbose: "Libia (Jamahiriya Libia Árabe Popular Socialista)" },
  { code: "LI", verbose: "Liechtenstein (Principado de)" },
  { code: "LT", verbose: "Lituania (República de)" },
  { code: "LU", verbose: "Luxemburgo (Gran Ducado de)" },
  { code: "MO", verbose: "Macao" },
  { code: "MK", verbose: "Macedonia (Antigua República Yugoslava de)" },
  { code: "MG", verbose: "Madagascar (República de)" },
  { code: "MY", verbose: "Malasia" },
  { code: "MW", verbose: "Malawi (República de)" },
  { code: "MV", verbose: "Maldivas (República de)" },
  { code: "ML", verbose: "Mali (República de)" },
  { code: "MT", verbose: "Malta (República de)" },
  { code: "MA", verbose: "Marruecos (Reino de)" },
  { code: "MQ", verbose: "Martinica (Departamento de Francia)" },
  { code: "MU", verbose: "Mauricio (República de)" },
  { code: "MR", verbose: "Mauritania (República Islámica de)" },
  { code: "YT", verbose: "Mayotte" },
  { code: "MX", verbose: "México (Estados Unidos Mexicanos) " },
  { code: "FM", verbose: "Micronesia" },
  { code: "MD", verbose: "Moldavia (República de)" },
  { code: "MC", verbose: "Mónaco (Principado de)" },
  { code: "MN", verbose: "Mongolia" },
  { code: "MS", verbose: "Monserrat (Isla)" },
  { code: "ME", verbose: "Montenegro" },
  { code: "MZ", verbose: "Mozambique (República de)" },
  { code: "MM", verbose: "Myanmar (Unión de)" },
  { code: "NA", verbose: "Namibia (República de)" },
  { code: "NR", verbose: "Nauru" },
  { code: "NP", verbose: "Nepal (Reino de)" },
  { code: "NI", verbose: "Nicaragua (República de)" },
  { code: "NE", verbose: "Níger (República de)" },
  { code: "NG", verbose: "Nigeria (República Federal de)" },
  { code: "NU", verbose: "Nive (Isla)" },
  { code: "NO", verbose: "Noruega (Reino de)" },
  { code: "NC", verbose: "Nueva Caledonia (Territorio Francés de Ultramar)" },
  { code: "NZ", verbose: "Nueva Zelandia" },
  { code: "OM", verbose: "Omán (Sultanato de)" },
  { code: "NL", verbose: "Países Bajos (Reino de Los) (Holanda)" },
  { code: "ZZ", verbose: "Países no declarados" },
  { code: "PK", verbose: "Pakistán (República Islámica de)" },
  { code: "PW", verbose: "Palau (República de)" },
  { code: "PS", verbose: "Palestina" },
  { code: "PA", verbose: "Panamá (República de)" },
  { code: "PG", verbose: "Papúa Nueva Guinea (Estado Independiente de)" },
  { code: "PY", verbose: "Paraguay (República del)" },
  { code: "PE", verbose: "Perú (República del)" },
  { code: "PF", verbose: "Polinesia Francesa" },
  { code: "PL", verbose: "Polonia (República de)" },
  { code: "PT", verbose: "Portugal (República Portuguesa)" },
  { code: "PR", verbose: "Puerto Rico (Estado Libre Asociado de la Comunidad de)" },
  { code: "QA", verbose: "Qatar (Estado de)" },
  { code: "GB", verbose: "Reino Unido de la Gran Bretaña e Irlanda del Norte " },
  { code: "CF", verbose: "República Centroafricana" },
  { code: "CZ", verbose: "República Checa" },
  { code: "DO", verbose: "República Dominicana" },
  { code: "RE", verbose: "Reunión (Departamento de la) (Francia)" },
  { code: "RW", verbose: "Ruanda" },
  { code: "RO", verbose: "Rumania" },
  { code: "RU", verbose: "Rusia (Federación Rusa)" },
  { code: "EH", verbose: "Sahara Occidental (República Árabe Saharavi Democrática)" },
  { code: "BL", verbose: "Saint Barthelemy" },
  { code: "MF", verbose: "Saint Martin" },
  { code: "WS", verbose: "Samoa (Estado Independiente de)" },
  { code: "AS", verbose: "Samoa Americana" },
  { code: "KN", verbose: "San Cristóbal y Nieves (Federación de) (San Kitts-Nevis)" },
  { code: "SM", verbose: "San Marino (Serenísima República de)" },
  { code: "PM", verbose: "San Pedro y Miquelón" },
  { code: "VC", verbose: "San Vicente y Las Granadinas " },
  { code: "SH", verbose: "Santa Elena" },
  { code: "LC", verbose: "Santa Lucia" },
  { code: "ST", verbose: "Santo Tome y Príncipe (República Democrática de)" },
  { code: "SN", verbose: "Senegal (República del)" },
  { code: "RS", verbose: "Serbia" },
  { code: "SC", verbose: "Seychelles (República de las)" },
  { code: "SL", verbose: "Sierra Leona (República de)" },
  { code: "SG", verbose: "Singapur (República de)" },
  { code: "SX", verbose: "Sint Maarten" },
  { code: "SY", verbose: "Siria (República Árabe)" },
  { code: "SO", verbose: "Somalia" },
  { code: "LK", verbose: "Sri Lanka (República Democrática Socialista de)" },
  { code: "SZ", verbose: "Suazilandia" },
  { code: "ZA", verbose: "Sudáfrica (República de)" },
  { code: "SD", verbose: "Sudan (República del)" },
  { code: "SS", verbose: "Sudan Sur" },
  { code: "SE", verbose: "Suecia (Reino de) " },
  { code: "CH", verbose: "Suiza (Confederación)" },
  { code: "SR", verbose: "Surinam (República de)" },
  { code: "SJ", verbose: "Svalbard y Jan Mayen" },
  { code: "TH", verbose: "Tailandia (Reino de)" },
  { code: "TW", verbose: "Taiwán (República de China)" },
  { code: "TZ", verbose: "Tanzania (República Unida de)" },
  { code: "TJ", verbose: "Tayikistán" },
  { code: "IO", verbose: "Territorios Británicos del Océano Índico" },
  { code: "TF", verbose: "Territorios Franceses del Sur" },
  { code: "TL", verbose: "Timor Oriental" },
  { code: "TG", verbose: "Togo (República Togolesa)" },
  { code: "TK", verbose: "Tokelau" },
  { code: "TO", verbose: "Tonga (Reino de)" },
  { code: "TT", verbose: "Trinidad y Tobago (República de)" },
  { code: "TN", verbose: "Túnez (República de)" },
  { code: "TM", verbose: "Turkmenistán (República de)" },
  { code: "TR", verbose: "Turquía (República de)" },
  { code: "TV", verbose: "Tuvalu (Comunidad Británica de Naciones)" },
  { code: "UA", verbose: "Ucrania" },
  { code: "UG", verbose: "Uganda (República de)" },
  { code: "UY", verbose: "Uruguay (República Oriental del)" },
  { code: "UZ", verbose: "Uzbekistán (República de)" },
  { code: "VU", verbose: "Vanuatu" },
  { code: "VE", verbose: "Venezuela (República de)" },
  { code: "VN", verbose: "Vietnam (República Socialista de)" },
  { code: "WF", verbose: "Wallis y Futuna" },
  { code: "YE", verbose: "Yemen (República de)" },
  { code: "DJ", verbose: "Yibuti" },
  { code: "ZM", verbose: "Zambia (República de)" },
  { code: "ZW", verbose: "Zimbabue (República de)" }
];

module.exports = {
  raw: rawCodes,
  pretty: rawCodes.map(function (country, index) {
    return (
      <option key={ index } value={ country.code }>{ country.verbose }</option>
    );
  }),
};
